tags = {
        '.mp3': {
            'album'               : 'TALB',
            'albumsort'           : 'TSOA',
            'title'               : 'TIT2',
            'titlesort'           : 'TSOT',
            'work'                : 'TOAL',
            'artist'              : 'TPE1',
            'artistsort'          : 'TSOP',
            'albumartist'         : 'TPE2',
            'albumartistsort'     : 'TSO2',
            'date'                : 'TDRC',
            'originaldate'        : 'TDOR',
            'composer'            : 'TCOM',
            'composersort'        : 'TSOC',
            'lyricist'            : 'TEXT',
            'writer'              : 'TXXX:Writer',
            'conductor'           : 'TPE3',
            'performer:instrument': 'TMCL:instrument',
            'remixer'             : 'TPE4',
            'arranger'            : 'TIPL:arranger',
            'engineer'            : 'TIPL:engineer',
            'producer'            : 'TIPL:producer',
            'djmixer'             : 'TIPL:DJ-mix',
            'mixer'               : 'TIPL:mix',
            'label'               : 'TPUB',
            'grouping'            : 'TIT1',
            'subtitle'            : 'TIT3',
            'discsubtitle'        : 'TSST',
            'tracknumber'         : 'TRCK',
            'totaltracks'         : 'TRCK',
            'discnumber'          : 'TPOS',
            'totaldiscs'          : 'TPOS',
            'compilation'         : 'TCMP',
            'comment:description' : 'COMM:description',
            'genre'               : 'TCON',
            '_rating'             : 'POPM',
            'bpm'                 : 'TBPM',
            'mood'                : 'TMOO',
            'lyrics:description'  : 'USLT:description',
            'media'               : 'TMED',
            'catalognumber'       : 'TXXX:CATALOGNUMBER',
            'releasestatus'       : 'TXXX:MusicBrainz Album Status',
            'releasetype'         : 'TXXX:MusicBrainz Album Type',
            'releasecountry'      : 'TXXX:MusicBrainz Album Release Country',
            'script'              : 'TXXX:SCRIPT',
            'language'            : 'TLAN',
            'copyright'           : 'TCOP',
            'license'             : 'WCOP',
            'encodedby'           : 'TENC',
            'encodersettings'     : 'TSSE',
            'barcode'             : 'TXXX:BARCODE',
            'isrc'                : 'TSRC',
            'asin'                : 'TXXX:ASIN',
            'albumart'            : 'APIC:',
            'musicbrainz_recordingid'    : 'UFID:http://musicbrainz.org',
            'musicbrainz_releasetrackid' : 'TXXX:MusicBrainz Release Track Id',
            'musicbrainz_albumid'        : 'TXXX:MusicBrainz Album Id',
            'musicbrainz_artistid'       : 'TXXX:MusicBrainz Artist Id',
            'musicbrainz_albumartistid'  : 'TXXX:MusicBrainz Album Artist Id',
            'musicbrainz_releasegroupid' : 'TXXX:MusicBrainz Release Group Id',
            'musicbrainz_workid'         : 'TXXX:MusicBrainz Work Id',
            'musicbrainz_trmid'          : 'TXXX:MusicBrainz TRM Id',
            'musicbrainz_discid'         : 'TXXX:MusicBrainz Disc Id',
            'acoustic_id'                : 'TXXX:Acoustic Id',
            'acousticid_fingerprint'     : 'TXXX:Acousticid Fingerprint',
            'musicip_puid'               : 'TXXX:MusicIP PUID',
            'website'                    : 'WOAR',
        },
        '.wma': {
            'artist'      : 'Author',
            'album'       : 'WM/AlbumTitle',
            'title'       : 'Title',
            'genre'       : 'WM/Genre',
            'year'        : 'WM/Year',
            'tracknumber' : 'WM/TrackNumber',
            'composer'    : 'WM/Composer',
            'publisher'   : 'WM/Publisher',
            'lyrics'      : 'WM/Lyrics',
            'albumartist' : 'WM/AlbumArtist',
            },
        '.wmv': {
            'artist'      : 'Author',
            'album'       : 'WM/AlbumTitle',
            'title'       : 'Title',
            'genre'       : 'WM/Genre',
            'year'        : 'WM/Year',
            'tracknumber' : 'WM/TrackNumber',
            'composer'    : 'WM/Composer',
            'publisher'   : 'WM/Publisher',
            'lyrics'      : 'WM/Lyrics',
            },
        '.m4a': {
            'album'               : '\xa9alb',
            'albumsort'           : 'soal',
            'title'               : '\xa9nam',
            'titlesort'           : 'sonm',
            'artist'              : '\xa9ART',
            'artistsort'          : 'soar',
            'albumartist'         : 'aART',
            'albumartistsort'     : 'soaa',
            'date'                : '\xa9day',
            'composer'            : '\xa9wrt',
            'composersort'        : 'soco',
            'lyricist'            : '----:com.apple.iTunes:LYRICIST',
            'conductor'           : '----:com.apple.iTunes:CONDUCTOR',
            'remixer'             : '----:com.apple.iTunes:REMIXER',
            'engineer'            : '----:com.apple.iTunes:ENGINEER',
            'producer'            : '----:com.apple.iTunes:PRODUCER',
            'djmixer'             : '----:com.apple.iTunes:DJMIXER',
            'mixer'               : '----:com.apple.iTunes:MIXER',
            'label'               : '----:com.apple.iTunes:LABEL',
            'grouping'            : '\xa9grp',
            'subtitle'            : '----:com.apple.iTunes:SUBTITLE',
            'discsubtitle'        : '----:com.apple.iTunes:DISCSUBTITLE',
            'tracknumber'         : 'trkn',
            'totaltracks'         : 'trkn',
            'discnumber'          : 'disk',
            'totaldiscs'          : 'disk',
            #'compilation'         : 'cpil',
            'comment'             : '\xa9cmt',
            'genre'               : '\xa9gen',
            'bpm'                 : 'tmpo',
            'mood'                : '----:com.apple.iTunes:MOOD',
            'lyrics'              : '\xa9lyr',
            'media'               : '----:com.apple.iTunes:MEDIA',
            'catalognumber'       : '----:com.apple.iTunes:CATALOGNUMBER',
            'show'                : 'tvsh',
            'showsort'            : 'sosn',
            'podcast'             : 'pcst',
            'podcasturl'          : 'purl',
            'releasestatus'       : '----:com.apple.iTunes:MusicBrainz Album Status',
            'releasetype'         : '----:com.apple.iTunes:MusicBrainz Album Type',
            'releasecountry'      : '----:com.apple.iTunes:MusicBrainz Album Release Country',
            'script'              : '----:com.apple.iTunes:SCRIPT',
            'language'            : '----:com.apple.iTunes:LANGUAGE',
            'copyright'           : 'cprt',
            'license'             : '----:com.apple.iTunes:LICENSE',
            'encodedby'           : '\xa9too',
            'barcode'             : '----:com.apple.iTunes:BARCODE',
            'isrc'                : '----:com.apple.iTunes:ISRC',
            'asin'                : '----:com.apple.iTunes:ASIN',
            'albumart'            : 'covr',
            'musicbrainz_recordingid'    : '----:com.apple.iTunes:MusicBrainz Track Id',
            'musicbrainz_releasetrackid' : '----:com.apple.iTunes:MusicBrainz Release Track Id',
            'musicbrainz_albumid'        : '----:com.apple.iTunes:MusicBrainz Album Id',
            'musicbrainz_artistid'       : '----:com.apple.iTunes:MusicBrainz Artist Id',
            'musicbrainz_albumartistid'  : '----:com.apple.iTunes:MusicBrainz Album Artist Id',
            'musicbrainz_releasegroupid' : '----:com.apple.iTunes:MusicBrainz Release Group Id',
            'musicbrainz_workid'         : '----:com.apple.iTunes:MusicBrainz Work Id',
            'musicbrainz_trmid'          : '----:com.apple.iTunes:MusicBrainz TRM Id',
            'musicbrainz_discid'         : '----:com.apple.iTunes:MusicBrainz Disc Id',
            'acoustic_id'                : '----:com.apple.iTunes:Acoustid Id',
            'acousticid_fingerprint'     : '----:com.apple.iTunes:Acoustid Fingerprint',
            'musicip_puid'               : '----:com.apple.iTunes:MusicIP PUID',
            },
        '.mp4': {
            'artist'      : '\xa9ART',
            'album'       : '\xa9alb',
            'title'       : '\xa9nam',
            'genre'       : '\xa9gen',
            'year'        : '\xa9day',
            'tracknumber' : 'trkn',
            'composer'    : '\xa9wrt',
            'lyrics'      : '\xa9lyr',
            'albumartist' : 'aART',
            'disk'        : 'disk',
            'comment'     : '\xa9cmt',
            'albumart'    : 'covr',
            },
        '.aac': {
            'artist'      : '\xa9ART',
            'album'       : '\xa9alb',
            'title'       : '\xa9nam',
            'genre'       : '\xa9gen',
            'year'        : '\xa9day',
            'tracknumber' : 'trkn',
            'composer'    : '\xa9wrt',
            'lyrics'      : '\xa9lyr',
            'albumartist' : 'aART',
            'disk'        : 'disk',
            'comment'     : '\xa9cmt',
            },
        '.ogg': {
            'artist'      : 'artist',
            'album'       : 'album',
            'title'       : 'title',
            'genre'       : 'genre',
            'year'        : 'date',
            'tracknumber' : 'tracknumber',
            'composer'    : 'composer',
            'albumart'    : 'metadata_block_picture',
            'lyrics'      : 'lyrics',
            },
        '.flac': {
            'artist'          : 'artist',
            'album'           : 'album',
            'title'           : 'title',
            'genre'           : 'genre',
            'year'            : 'date',
            'originaldate'    : 'originaldate',
            'originalyear'    : 'originalyear',
            'tracknumber'     : 'tracknumber',
            'totaltracks'     : 'totaltracks',
            'discnumber'      : 'discnumber',
            'totaldiscs'      : 'totaldiscs',
            'bpm'             : 'bpm',
            'mood'            : 'mood',
            'composer'        : 'composer',
            'albumartist'     : 'albumartist',
            'lyricist'        : 'lyricist',
            'writer'          : 'writer',
            'conductor'       : 'conductor',
            'remixer'         : 'remixer',
            'arranger'        : 'arranger',
            'engineer'        : 'engineer',
            'producer'        : 'producer',
            'djmixer'         : 'djmixer',
            'mixer'           : 'mixer',
            'label'           : 'label',
            'catalognumber'   : 'catalognumber',
            'grouping'        : 'grouping',
            'subtitle'        : 'subtitle',
            'discsubtitle'    : 'discsubtitle',
            'compilation'     : 'compilation',
            'comment'         : 'comment',
            'albumart'        : 'metadata_block_picture',
            'lyrics'          : 'lyrics',
            'albumsort'       : 'albumsort',
            'titlesort'       : 'titlesort',
            'artistsort'      : 'artistsort',
            'albumartistsort' : 'albumartistsort',
            'composersort'    : 'composersort',
            'work'            : 'work',
            'releasestatus'   : 'releasestatus',
            'releasetype'     : 'releasetype',
            'releasecountry'  : 'releasecountry',
            'script'          : 'script',
            'language'        : 'language',
            'copyright'       : 'copyright',
            'license'         : 'license',
            'barcode'         : 'barcode',
            'isrc'            : 'isrc',
            'asin'            : 'asin',
            'musicbrainz_trackid'        : 'musicbrainz_trackid',
            'musicbrainz_releasetrackid' : 'musicbrainz_releasetrackid',
            'musicbrainz_albumid'        : 'musicbrainz_albumid',
            'musicbrainz_artistid'       : 'musicbrainz_artistid',
            'musicbrainz_albumartistid'  : 'musicbrainz_albumartistid',
            'musicbrainz_releasegroupid' : 'musicbrainz_releasegroupid',
            'musicbrainz_workid'         : 'musicbrainz_workid',
            'musicbrainz_trmid'          : 'musicbrainz_trmid',
            'musicbrainz_discid'         : 'musicbrainz_discid',
            'acoustic_id'                : 'acoustic_id',
            'acousticid_fingerprint'     : 'acousticid_fingerprint',
            'musicip_puid'               : 'musicp_puid',
            },
        '.mpc': {
            'artist'      : 'Artist',
            'album'       : 'Album',
            'title'       : 'Title',
            'genre'       : 'Genre',
            'year'        : 'Year',
            'tracknumber' : 'Track',
            'composer'    : 'Composer',
            },
        '.3gp': {
            'artist'      : '\xa9ART',
            'album'       : '\xa9alb',
            'title'       : '\xa9nam',
            'genre'       : '\xa9gen',
            'year'        : '\xa9day',
            'tracknumber' : 'trkn',
            'composer'    : '\xa9wrt',
            'lyrics'      : '\xa9lyr',
            'albumartist' : 'aART',
            'disk'        : 'disk',
            'comment'     : '\xa9cmt',
            'albumart'    : 'covr',
            },
        '.wv': {
            'artist'      : 'artist',
            'album'       : 'album',
            'title'       : 'title',
            'genre'       : 'genre',
            'year'        : 'year',
            'tracknumber' : 'track',
            }
        }
